name: Android CI
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platforms;android-30'
          ndk-version: '21.3.6528147'
          sdk-build-tools: '30.0.3'
      - name: Build with Gradle
        run: ./gradlew test --stacktrace

  build:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: 'platforms;android-30'
        ndk-version: '21.3.6528147'
        sdk-build-tools: '30.0.3'
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk


